# Generated by Django 3.2.4 on 2021-06-16 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkbox', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ImageFile')),
            ],
        ),
    ]
